#!/usr/bin/env python3
"""
Custom character editor for the 16x64 reader board (readerBoardMinima.ino).

Draw a picture on a 16-row grid, attach it to a keyboard character, and the
tool writes custom_chars.h next to the sketch. Re-upload the sketch and any
message containing that character shows your picture instead of the letter.

    Left-click / drag   paint with the selected color
    Right-click / drag  erase a pixel

Colors: "Message color" pixels follow whatever color is chosen in the board's
serial menu. Any other swatch (or a custom color) is a fixed color that always
shows as drawn.

Glyphs are stored in custom_chars.json (editable source) and exported to
custom_chars.h (what the sketch includes). Both are rewritten on every
Save / Delete.

Run: /opt/homebrew/bin/python3 custom_char_editor.py
"""

import json
import os
import tkinter as tk
from tkinter import ttk, messagebox, colorchooser

ROWS = 16            # display height; glyphs are always full height
MAX_WIDTH = 64       # widest glyph (the display is 64 columns)
CELL = 14            # editor cell size in pixels
HERE = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(HERE, "custom_chars.json")
HEADER_PATH = os.path.join(HERE, "custom_chars.h")

# Pixel values: 0 = off, THEME = message color, anything else = 0xRRGGBB.
OFF = 0
THEME = 0x01000000   # must match CUSTOM_THEME in the sketch

BG = "#111111"
EMPTY = "#2a2a2a"
THEME_SHOWN = "#ff5000"   # how "message color" pixels are drawn here

PALETTE = [
    ("Message color", THEME),
    ("Red", 0xFF0000),
    ("Orange", 0xFF5000),
    ("Yellow", 0xFFC800),
    ("Green", 0x00FF00),
    ("Cyan", 0x00FFFF),
    ("Blue", 0x0000FF),
    ("Purple", 0x8C00FF),
    ("Pink", 0xFF2878),
    ("White", 0xFFFFFF),
]


def shown(value):
    """Tk color string for a pixel value."""
    if value == OFF:
        return EMPTY
    if value == THEME:
        return THEME_SHOWN
    return "#%06x" % value


class Glyph:
    """px[x][y] is a pixel value (see above); y = 0 is the top row."""

    def __init__(self, width=8, px=None):
        self.width = width
        self.px = [list(col) for col in px] if px else [[OFF] * ROWS for _ in range(width)]

    def copy(self):
        return Glyph(self.width, self.px)

    def is_empty(self):
        return not any(v for col in self.px for v in col)

    def resize(self, width):
        self.px = (self.px + [[OFF] * ROWS for _ in range(width)])[:width]
        self.width = width


def load_glyphs():
    if not os.path.exists(JSON_PATH):
        return {}
    with open(JSON_PATH) as f:
        raw = json.load(f)
    return {ch: Glyph(len(px), px) for ch, px in raw.items()}


def c_char(ch):
    return {"\\": "'\\\\'", "'": "'\\''"}.get(ch, "'%s'" % ch)


def save_glyphs(glyphs):
    with open(JSON_PATH, "w") as f:
        json.dump({ch: g.px for ch, g in sorted(glyphs.items())}, f)

    lines = [
        "// Generated by custom_char_editor.py - do not edit by hand.",
        "// Each glyph is width*16 pixels, column-major (top row first).",
        "// 0 = off, CUSTOM_THEME = message color, otherwise 0xRRGGBB.",
        "",
    ]
    entries = []
    for i, (ch, g) in enumerate(sorted(glyphs.items())):
        values = [v for col in g.px for v in col]
        body = ",\n  ".join(
            ", ".join("0x%08X" % v for v in values[j:j + ROWS]) for j in range(0, len(values), ROWS))
        lines.append("static const uint32_t customPix%d[] PROGMEM = {\n  %s\n};" % (i, body))
        entries.append("  { %s, %d, customPix%d }," % (c_char(ch), g.width, i))
    lines.append("")
    if entries:
        lines.append("static const CustomChar customChars[] = {")
        lines.extend(entries)
        lines.append("};")
    else:
        lines.append("static const CustomChar customChars[] = { { 0, 0, nullptr } };")
    lines.append("#define NUM_CUSTOM_CHARS %d" % len(entries))
    with open(HEADER_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")


class Editor(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Reader Board - Custom Characters")
        self.configure(bg=BG)
        self.resizable(False, False)

        self.glyphs = load_glyphs()
        self.glyph = Glyph(8)
        self.color = THEME           # currently selected paint color
        self.drag_value = None       # value being painted during a drag

        self.char_var = tk.StringVar(value="!")
        self.width_var = tk.IntVar(value=self.glyph.width)
        self.status_var = tk.StringVar(value="Left-click paints, right-click erases.")

        self._build()
        self._select_color(THEME)
        self._redraw()
        self._refresh_list()

    # ── UI ────────────────────────────────────────────────────────────────────
    def _build(self):
        left = tk.Frame(self, bg=BG)
        left.grid(row=0, column=0, padx=12, pady=12, sticky="n")

        self.canvas = tk.Canvas(left, width=MAX_WIDTH * CELL, height=ROWS * CELL,
                                bg=BG, highlightthickness=0)
        self.canvas.pack()
        self.canvas.bind("<Button-1>", lambda e: self._paint(e, start=True))
        self.canvas.bind("<B1-Motion>", lambda e: self._paint(e))
        for seq in ("<Button-2>", "<Button-3>"):
            self.canvas.bind(seq, lambda e: self._erase(e))
        for seq in ("<B2-Motion>", "<B3-Motion>"):
            self.canvas.bind(seq, lambda e: self._erase(e))

        # Color swatches
        palette = tk.Frame(left, bg=BG)
        palette.pack(pady=(10, 0), anchor="w")
        tk.Label(palette, text="Color:", bg=BG, fg="#aaaaaa").pack(side="left", padx=(0, 6))
        self.swatches = {}
        for name, value in PALETTE:
            sw = tk.Label(palette, width=3, height=1, bg=shown(value), bd=3, relief="flat")
            if value == THEME:
                sw.configure(text="M", fg="white")
            sw.pack(side="left", padx=2)
            sw.bind("<Button-1>", lambda e, v=value: self._select_color(v))
            self.swatches[value] = sw
        ttk.Button(palette, text="Custom...", command=self._pick_custom).pack(side="left", padx=(8, 0))
        self.custom_swatch = tk.Label(palette, width=3, bg=EMPTY, bd=3, relief="flat")
        self.custom_swatch.pack(side="left", padx=2)
        self.custom_swatch.bind("<Button-1>", lambda e: self._select_color(self.custom_value)
                                if getattr(self, "custom_value", None) else None)

        self.color_label = tk.Label(left, text="", bg=BG, fg="#aaaaaa", anchor="w")
        self.color_label.pack(fill="x", pady=(2, 0))

        tk.Label(left, text="Preview (actual size on the board)", bg=BG, fg="#aaaaaa").pack(pady=(8, 2))
        self.preview = tk.Canvas(left, width=MAX_WIDTH * 6, height=ROWS * 6,
                                 bg=BG, highlightthickness=1, highlightbackground="#444444")
        self.preview.pack()

        controls = tk.Frame(left, bg=BG)
        controls.pack(pady=10, fill="x")
        ttk.Label(controls, text="Character:").grid(row=0, column=0, sticky="w")
        ttk.Entry(controls, textvariable=self.char_var, width=3).grid(row=0, column=1, padx=(4, 16))
        ttk.Label(controls, text="Width:").grid(row=0, column=2, sticky="w")
        ttk.Spinbox(controls, from_=1, to=MAX_WIDTH, width=4, textvariable=self.width_var,
                    command=self._on_width).grid(row=0, column=3, padx=4)
        self.width_var.trace_add("write", lambda *_: self._on_width())

        tools = tk.Frame(left, bg=BG)
        tools.pack(fill="x")
        for text, cmd in [("Clear", self._clear), ("Fill all", self._fill_all),
                          ("Recolor", self._recolor), ("Mirror", self._mirror),
                          ("←", lambda: self._shift(-1, 0)), ("→", lambda: self._shift(1, 0)),
                          ("↑", lambda: self._shift(0, -1)), ("↓", lambda: self._shift(0, 1))]:
            ttk.Button(tools, text=text, width=8 if len(text) > 1 else 3, command=cmd).pack(side="left", padx=2)

        actions = tk.Frame(left, bg=BG)
        actions.pack(pady=(10, 0), fill="x")
        ttk.Button(actions, text="Save to character", command=self._save).pack(side="left", padx=2)
        ttk.Button(actions, text="Delete character", command=self._delete).pack(side="left", padx=2)

        tk.Label(left, textvariable=self.status_var, bg=BG, fg="#aaaaaa", anchor="w").pack(fill="x", pady=(10, 0))

        right = tk.Frame(self, bg=BG)
        right.grid(row=0, column=1, padx=(0, 12), pady=12, sticky="ns")
        tk.Label(right, text="Saved characters", bg=BG, fg="#aaaaaa").pack(anchor="w")
        self.listbox = tk.Listbox(right, width=22, height=24, exportselection=False)
        self.listbox.pack(fill="y", expand=True)
        self.listbox.bind("<<ListboxSelect>>", self._on_select)

    # ── Color selection ───────────────────────────────────────────────────────
    def _select_color(self, value):
        self.color = value
        for v, sw in self.swatches.items():
            sw.configure(relief="solid" if v == value else "flat")
        custom_selected = value not in self.swatches
        self.custom_swatch.configure(relief="solid" if custom_selected else "flat")
        if value == THEME:
            self.color_label.configure(text="Painting with: message color (follows the board's color menu)")
        else:
            self.color_label.configure(text="Painting with: fixed color #%06X" % value)

    def _pick_custom(self):
        rgb, _hex = colorchooser.askcolor(color=shown(self.color) if self.color else "#ffffff",
                                          title="Pick a color")
        if rgb is None:
            return
        value = (int(rgb[0]) << 16) | (int(rgb[1]) << 8) | int(rgb[2])
        if value == OFF:
            messagebox.showinfo("Color", "Pure black is the same as off - use right-click to erase.")
            return
        self.custom_value = value
        self.custom_swatch.configure(bg=shown(value))
        self._select_color(value)

    # ── Drawing ───────────────────────────────────────────────────────────────
    def _redraw(self):
        c = self.canvas
        c.delete("all")
        for x in range(MAX_WIDTH):
            for y in range(ROWS):
                if x < self.glyph.width:
                    value = self.glyph.px[x][y]
                    color = shown(value)
                else:
                    value, color = OFF, BG
                c.create_rectangle(x * CELL + 1, y * CELL + 1, (x + 1) * CELL - 1, (y + 1) * CELL - 1,
                                   fill=color, outline="")
                if value == THEME:   # marker so message-color pixels differ from a fixed orange
                    cx, cy = x * CELL + CELL // 2, y * CELL + CELL // 2
                    c.create_oval(cx - 2, cy - 2, cx + 2, cy + 2, fill="white", outline="")
        p = self.preview
        p.delete("all")
        for x in range(self.glyph.width):
            for y in range(ROWS):
                v = self.glyph.px[x][y]
                if v:
                    p.create_rectangle(x * 6 + 1, y * 6 + 1, x * 6 + 5, y * 6 + 5, fill=shown(v), outline="")

    def _cell(self, event):
        x, y = event.x // CELL, event.y // CELL
        if 0 <= x < self.glyph.width and 0 <= y < ROWS:
            return x, y
        return None

    def _paint(self, event, start=False):
        cell = self._cell(event)
        if cell is None:
            return
        x, y = cell
        if start:  # clicking a cell that already has this color erases it; otherwise paint
            self.drag_value = OFF if self.glyph.px[x][y] == self.color else self.color
        if self.drag_value is None:
            return
        self.glyph.px[x][y] = self.drag_value
        self._redraw()

    def _erase(self, event):
        cell = self._cell(event)
        if cell is None:
            return
        self.glyph.px[cell[0]][cell[1]] = OFF
        self._redraw()

    def _on_width(self):
        try:
            w = int(self.width_var.get())
        except (tk.TclError, ValueError):
            return
        if 1 <= w <= MAX_WIDTH and w != self.glyph.width:
            self.glyph.resize(w)
            self._redraw()

    # ── Edit tools ────────────────────────────────────────────────────────────
    def _clear(self):
        self.glyph = Glyph(self.glyph.width)
        self._redraw()

    def _fill_all(self):
        self.glyph.px = [[self.color] * ROWS for _ in range(self.glyph.width)]
        self._redraw()

    def _recolor(self):
        """Change every lit pixel to the selected color."""
        self.glyph.px = [[self.color if v else OFF for v in col] for col in self.glyph.px]
        self._redraw()

    def _mirror(self):
        self.glyph.px.reverse()
        self._redraw()

    def _shift(self, dx, dy):
        w = self.glyph.width
        new = [[OFF] * ROWS for _ in range(w)]
        for x in range(w):
            for y in range(ROWS):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w and 0 <= ny < ROWS:
                    new[nx][ny] = self.glyph.px[x][y]
        self.glyph.px = new
        self._redraw()

    # ── Saved characters ──────────────────────────────────────────────────────
    def _refresh_list(self, select=None):
        self.listbox.delete(0, "end")
        keys = sorted(self.glyphs)
        for ch in keys:
            self.listbox.insert("end", "  %s    (%d wide)" % (ch, self.glyphs[ch].width))
        if select in keys:
            self.listbox.selection_set(keys.index(select))

    def _on_select(self, _event):
        sel = self.listbox.curselection()
        if not sel:
            return
        ch = sorted(self.glyphs)[sel[0]]
        self.glyph = self.glyphs[ch].copy()
        self.char_var.set(ch)
        self.width_var.set(self.glyph.width)
        self._redraw()
        self.status_var.set("Loaded '%s'." % ch)

    def _current_char(self):
        ch = self.char_var.get()
        if len(ch) != 1 or not 33 <= ord(ch) <= 126:
            messagebox.showerror("Character", "Enter a single printable character (not a space).")
            return None
        return ch

    def _save(self):
        ch = self._current_char()
        if ch is None:
            return
        if self.glyph.is_empty():
            messagebox.showerror("Empty", "Draw something first.")
            return
        replacing = ch in self.glyphs
        self.glyphs[ch] = self.glyph.copy()
        save_glyphs(self.glyphs)
        self._refresh_list(select=ch)
        self.status_var.set("%s '%s'. Wrote custom_chars.h - re-upload the sketch." %
                            ("Updated" if replacing else "Saved", ch))

    def _delete(self):
        ch = self._current_char()
        if ch is None:
            return
        if ch not in self.glyphs:
            self.status_var.set("'%s' has no saved glyph." % ch)
            return
        del self.glyphs[ch]
        save_glyphs(self.glyphs)
        self._refresh_list()
        self.status_var.set("Deleted '%s'. Re-upload the sketch." % ch)


if __name__ == "__main__":
    Editor().mainloop()
